import type { Metadata } from "next";
import "./globals.css";
import Mheader from "./components/header/page";
import Footer from "./components/footer/page";

export const metadata: Metadata = {
  title: "Barbearia Malaman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Mheader />
        <div className="bg-yellow-100 relative">
          <div className="bg-[url('/images/bg-total.png')] absolute inset-0 opacity-15">
          </div>
            <div className="relative">
              {children}
            </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
