import type { Metadata } from "next";
import "./globals.css";
import Mheader from "./components/header/page";
import Footer from "./components/footer/page";

export const metadata: Metadata = {
  title: "Barbearia Malaman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Mheader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
